config/routes.rb
AllAboutMe::Application.routes.draw do
  resources :favorite_web_things

  resources :posts

  get "/index" => 'static_pages#index'
  get "/about" => 'static_pages#about'
  get "/contact" => 'static_pages#contact'

  root 'static_pages#index'

  

end

app/models/favorite_web_thing.rb
class FavoriteWebThing < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorite_web_things_controller.rb
class FavoriteWebThingsController < ApplicationController
  before_action :set_favorite_web_thing, only: [:show, :edit, :update, :destroy]

  # GET /favorite_web_things
  # GET /favorite_web_things.json
  def index
    @favorite_web_things = FavoriteWebThing.all
  end

  # GET /favorite_web_things/1
  # GET /favorite_web_things/1.json
  def show
  end

  # GET /favorite_web_things/new
  def new
    @favorite_web_thing = FavoriteWebThing.new
  end

  # GET /favorite_web_things/1/edit
  def edit
  end

  # POST /favorite_web_things
  # POST /favorite_web_things.json
  def create
    @favorite_web_thing = FavoriteWebThing.new(favorite_web_thing_params)

    respond_to do |format|
      if @favorite_web_thing.save
        format.html { redirect_to @favorite_web_thing, notice: 'Favorite web thing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @favorite_web_thing }
      else
        format.html { render action: 'new' }
        format.json { render json: @favorite_web_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorite_web_things/1
  # PATCH/PUT /favorite_web_things/1.json
  def update
    respond_to do |format|
      if @favorite_web_thing.update(favorite_web_thing_params)
        format.html { redirect_to @favorite_web_thing, notice: 'Favorite web thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @favorite_web_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorite_web_things/1
  # DELETE /favorite_web_things/1.json
  def destroy
    @favorite_web_thing.destroy
    respond_to do |format|
      format.html { redirect_to favorite_web_things_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite_web_thing
      @favorite_web_thing = FavoriteWebThing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_web_thing_params
      params.require(:favorite_web_thing).permit(:title, :body, :img_url, :url)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :date)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @posts = Post.order('created_at desc').limit(3)
    @fav_webbys = FavoriteWebThing.order("RANDOM()").limit(3)
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_web_things_helper.rb
module FavoriteWebThingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/favorite_web_things/_form.html.erb
<%= form_for(@favorite_web_thing) do |f| %>
  <% if @favorite_web_thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite_web_thing.errors.count, "error") %> prohibited this favorite_web_thing from being saved:</h2>

      <ul>
      <% @favorite_web_thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorite_web_things/edit.html.erb
<h1>Editing favorite_web_thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite_web_thing %> |
<%= link_to 'Back', favorite_web_things_path %>

app/views/favorite_web_things/index.html.erb
<h1>My Favorite Webby Things</h1>
<%= link_to 'New Favorite web thing', new_favorite_web_thing_path, class: "button small" %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Img url</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @favorite_web_things.each do |favorite_web_thing| %>
      <tr>
        <td><%= favorite_web_thing.title %></td>
        <td><%= favorite_web_thing.body %></td>
        <td><%= favorite_web_thing.img_url %></td>
        <td><%= favorite_web_thing.url %></td>
        <td><%= link_to 'Show', favorite_web_thing %></td>
        <td><%= link_to 'Edit', edit_favorite_web_thing_path(favorite_web_thing) %></td>
        <td><%= link_to 'Destroy', favorite_web_thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/favorite_web_things/new.html.erb
<h1>New favorite_web_thing</h1>

<%= render 'form' %>

<%= link_to 'Back', favorite_web_things_path %>

app/views/favorite_web_things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @favorite_web_thing.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @favorite_web_thing.body %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @favorite_web_thing.img_url %>
</p>

<p>
  <strong>Url:</strong>
  <%= @favorite_web_thing.url %>
</p>

<%= link_to 'Edit', edit_favorite_web_thing_path(@favorite_web_thing) %> |
<%= link_to 'Back', favorite_web_things_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>The Modern Day Renaissance Agrarian</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar top-margin" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Modern Renaissance Agrarian", root_path %></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
      </ul>
      
      <section class="top-bar-section">
        <ul class="right">
          <li><%= link_to "About Mike", about_path %></li>
          <li><%= link_to "Contact Mike", contact_path %>
          <!-- To do a dropdown:
          <li class="has-dropdown">
            <a href="#">Button with dropdown</a>
            <ul class="dropdown">
              <li><a href="#">First link</a></li>
              <li><a href="#">Second link</a></li>
            </ul>
          </li> -->
        </ul>


      </section>
    </nav>
    <div class="row first">
      <%= yield %>
      <%= javascript_include_tag "application" %>
      <footer class="small-12 columns">
        <p>Copyright <%= DateTime.now.strftime("%Y") %>, Mike Vezzani</p>
      </footer>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :rows => 10 %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= raw(post.body.truncate(155, separator: ' ', omission: '...')) %></td>
        <td><%= post.date %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, class: "button small round" %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="small-6 medium-6 large-6 columns">
    <p>
      <strong><%= @post.title %></strong>
    </p>
  </div>
  <div class="small-6 medium-6 large-6 columns">
    <p><%= @post.date %></p>
  </div>
</div>
<p>
  <%= raw(@post.body) %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/static_pages/about.html.erb
<h1>The Better Mike Project</h1>
<h1><small>Writing to a better Me. Each Day.</small></h1>
<h2>About Mike</h2>
<p>Hi! I'm Mike, a liberal arts graduate, agricultural and environmental advocate,
    and all around easy-going dude. I love music, and I particularly enjoy the opportunity
    to jam with other musicians when I have the opportunity. I have (what I've coined as) 
    hobby ADHD. I love to learn. I could spend hours watching youtube videos on blacksmithing
    or archery. I love the outdoors. Camping in tents is the best. Hiking with gear on my
    back makes me smile.
</p>
<p>But what I'm passionate about is land. I love to garden. Growing stuff in my own garden
    gives me a sense of connection to our earth that nothing else does. A good friend of 
    mine once referenced me to the works of Wendell Berry. His writings were like a tender,
    delicious steak; his ideas like a refreshing glass of lemonade. As I poured over the
    books I had purchased, something inside me sparked. I have found my passion. I have 
    found my life's pursuit of happiness. I want to become a steward of the land. I want
    to feed my family food that not only fills them, but makes them happy. And I want to
    show others around me how this is possible. 
</p>
<p>Hi! I'm Mike, a liberal arts graduate, agricultural and environmental advocate,
    and all around easy-going dude. I love music, and I particularly enjoy the opportunity
    to jam with other musicians when I have the opportunity. I have (what I've coined as) 
    hobby ADHD. I love to learn. I could spend hours watching youtube videos on blacksmithing
    or archery. I love the outdoors. Camping in tents is the best. Hiking with gear on my
    back makes me smile.
</p>
<p>But what I'm passionate about is land. I love to garden. Growing stuff in my own garden
    gives me a sense of connection to our earth that nothing else does. A good friend of 
    mine once referenced me to the works of Wendell Berry. His writings were like a tender,
    delicious steak; his ideas like a refreshing glass of lemonade. As I poured over the
    books I had purchased, something inside me sparked. I have found my passion. I have 
    found my life's pursuit of happiness. I want to become a steward of the land. I want
    to feed my family food that not only fills them, but makes them happy. And I want to
    show others around me how this is possible. 
</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/index.html.erb
<div class="small-12 medium-12 large-12 columns">
  <div class="panel add-rounded-corners-sm">
    <h2>The Modern Day Renaissance Agrarian</h2>
    <hr />
    <div class="row">
      <div class="small-12 medium-6 large-9 columns blue">
        <h2><small>My name is Mike. I love life and am passionate about sustainable agriculture.
        I relax listening to Jimmy Smith and Freddy Mercury, reading Wendell Berry and Michael Pollan,
        and watching Stephen Colbert and Zak Orth. I am uncomfortable when I'm not learning or working
        with my hands.</small></h2>
      </div>
      <div class="small-12 medium-6 large-3 columns">
        <%= image_tag("profile.jpg", class: "th") %>
      </div>
    </div>
  </div>
</div>
<div class="small-12 medium-8 large-8 columns">
  <h2>Recent blog entries:</h2>
  <% @posts.each do |p| %>
    <div class="blog-snippet">
      <div class="row">
        <div class="small-8 columns">
          <h3><%= link_to "#{p.title}", post_path(p) %></h3>
        </div>
        <div class="small-4 columns">
          <h4><%= p.date %></h4>
        </div>
      </div>
      <p><%= raw(p.body.truncate(305, separator: ' ', omission: "...")) %></p>
      <p><%= link_to "Read More", p %></p>
    </div>
  <% end %>
</div>
<aside class="small-12 medium-4 large-4 columns horizontal-rule-left">
  <h4>Favorite Webby Things:</h4>
  <% @fav_webbys.each do |f| %>
    <a href=<%="#{f.url}"%>>
      <div class="top-bottom-border">
        <%= image_tag("#{f.img_url}", class: "th") %>
        <h5><%= f.title %></h5>
        <p><%= f.body %></p>
      </div>
    </a>
  <% end %>
</aside>